# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img_sponsor', models.ImageField(upload_to='img_sponsors')),
                ('country', models.CharField(max_length=60)),
            ],
        ),
    ]
