# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181120_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img_event',
            field=models.ImageField(blank=True, upload_to='img_events'),
        ),
    ]
