# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('avatar', models.ImageField(upload_to='avatars_competitors')),
                ('country', models.CharField(max_length=120)),
                ('wca_id', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('competitions', models.PositiveIntegerField(default=0)),
                ('solves', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
